# Site settings
title: For Code's Sake
header-img: img/home-bg.png
email: tony.mastrorio@gmail.com
copyright_name: tonymastrorio
description: > # this means to ignore newlines until "baseurl:"
  Craft Beer and Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tonymastrorio
learn_profile: tonymastrorio
email_username: tony.mastrorio@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
